keywords[
    {"key":"label","value": "1"},
    {"key":"invoice","value": "1"},
    {"key":"post","value": "1"},
    {"key":"document","value": "3"},
    {"key":"postal","value": "1"},
    {"key":"calculations","value": "2"},
    {"key":"copy","value": "2"},
    {"key":"fedex","value": "3"},
    {"key":"statement","value": "5"},
    {"key":"financial","value": "4"},
    {"key":"dhl","value": "3"},
    {"key":"usps","value": "3"},
    {"key":"eight","value": "3"},
    {"key":"notification","value": "1"},
    {"key":"Change Password","value": "5"},
    {"key":"irs","value": "5"},
    {"key":"ups","value": "5"},
    {"key":"no","value": "3"},
    {"key":"delivery","value": "2"},
    {"key":"ticket","value": "3"},
    {"key":"assist urgently","value": "1"},
    {"key":"document shared with you","value": "5"},
    {"key":"bank of","value": "5"},
    {"key":"verify your account","value": "5"},
    {"key":"document copy","value": "5"},
    {"key":"action required","value": "3"},
    {"key":"order number","value": "5"},
    {"key":"pre-approved","value": "5"},
    {"key":"signiture","value": "5"},
    {"key":"required","value": "4"},
    {"key":"login","value": "5"}
 ]